### ISSUE TITLE
Pinning failed

### ISSUE THREAD

**Issue by agmap** [nftstorage/NFT.Storage-Flagship-Preservation-Public-Good#2]
CID is pinned and getting status "pinning failed"
Add retry for uploaded CID with status “Pinning failed”.
![image](https://github.com/user-attachments/assets/a2690b9d-81d3-47a3-9f7c-fefe425e872f)
I can check the pinning status here:
https://delegated-ipfs.dev/routing/v1/providers/bafybeifkrphyxq65xaguiiqqgow7ogcxb4ci3p7akxojqfh3qrzhai633m

**Comment by elizabeth-griffiths** [comment]
Hi there, 
Can you please explain this issue with more detail? I don't quite follow. 
Thanks!

**Comment by agmap** [comment]
I have uploaded some CIDs, and for some the message “pinning failed” appears.
But when I check it, it is pinned and can be opened within the ipfs network.

**Comment by agmap** [comment]
Lighthouse having the same issues with migrating the some CIDs. But when I check with ipfs-desktop, kubo node, helia node,  https://delegated-ipfs.dev/routing/v1/providers/<CID>... or https://cid.contact/cid/<CID> I can contact and load the CID.

**Comment by elizabeth-griffiths** [comment]
"Lighthouse having the same issues with migrating the some CIDs." --> What do you mean? They are not able to download the CIDs? I can put you in touch with the Lighthouse team directly, if that would help?

We are also going to retry all failed pins on our side. I'll let you know when this is done.

**Comment by agmap** [comment]
I'm so grateful for all your wonderful support. It means a lot!
Lighthouse also have problems migrating my CIDs. I'm in touch with them.
I don't have a local copy of the data. It must be fetched directly from native IPFS nodes or gateways.
This is very hard, and I'm glad you're helping. 
You can check whether pinning is still available here.
https://delegated-ipfs.dev/routing/v1/providers/<CID>
Some CIDs are too big to preserve.

**Comment by elizabeth-griffiths** [comment]
Hi agmap - We've retried all pins. Please check your status. If there are still failed pins, the most likely cause is that you need to buy more storage. I'm going to close this, but feel free to re-open if needed.

**Comment by agmap** [comment]
Thank you very much. 😊
Yes, most of the CIDs should be imported. 👍
What happens to the other non-imported CIDs, which may be too large or no longer have pinning or are double uploads? Many CIDs in my account are still "in quene". Can these be cancelled automatically? It would also be nice if there was a cancel button that could be used in the "in quene" status. 
![image](https://github.com/user-attachments/assets/e4ceec6b-5ed6-4a67-9adf-82a922141c72)

**Comment by agmap** [comment]
The import still fails when the CIDs are provided by "graphsync-filecoinv1" 
https://specs.ipfs.tech/routing/http-routing-v1/#graphsync-schema

Example:
QmbxUjT4F9UeUyMcN1ZFUQte4d8q4zjPnEBXaQSTtXuMGL
https://delegated-ipfs.dev/routing/v1/providers/QmbxUjT4F9UeUyMcN1ZFUQte4d8q4zjPnEBXaQSTtXuMGL

There are providers:
![image](https://github.com/user-attachments/assets/67341208-1ad8-4674-ab8d-b9d4acc1aac4)
