### ISSUE TITLE
Filecoin deals in GUI and API (Fetching...)

### ISSUE THREAD

**Issue by agmap** [nftstorage/NFT.Storage-Flagship-Preservation-Public-Good#6]
I've imported a lot of CIDs and many of them have now received Filecoin deals. Thanks a lot! 👍
The nft.storage GUI only shows the Filecoin deal numbers up to item 3,500. After that, it only shows "Fetching...", even though they have received a Filecoin deal.
I think it would be great if I could query this through the API.
![image](https://github.com/user-attachments/assets/ddd29a38-2c8a-4436-860a-7e4128940a9a)

**Comment by elizabeth-griffiths** [comment]
Update: This is in the sprint to get fixed.

**Comment by elizabeth-griffiths** [comment]
The team is currently working on this. We're aiming to have it complete this week.

**Comment by agmap** [comment]
I just wanted to let you know that I've tested it and it works perfectly now, even above 3,500.
I'm really grateful for that. Thank you so much! 🙏

**Comment by elizabeth-griffiths** [comment]
Confirming that this is resolved now.
