### ISSUE TITLE
Retrieving my long-term stored CIDs (stored with Filecoin deals)

### ISSUE THREAD

**Issue by agmap** [nftstorage/NFT.Storage-Flagship-Preservation-Public-Good#7]
Suppose I lose my pinning with some of my hot storage providers. 
How can I retrieve my CIDs that are stored long-term in Filecoin network with nft.storage?

**Comment by elizabeth-griffiths** [comment]
Here's the information about this: https://app.nft.storage/v1/docs/how-to/filecoin-retrieval

In August we will complete testing with our storage provider to validate that NFT.Storage the Filecoin Storage Provider with the 1 unsealed deal with each CID makes that CID available across ipfs.io as well. (There was a blocker in a 3rd party software called Boost that has just made this possible.)

**Comment by agmap** [comment]
I'm so sorry! I completely overlooked this information. I'm really excited about it, thank you so much for letting me know!
